version: '3.8'

services:

  app:
    container_name: app
    build:
      context: ./bura-app
      target: development
    depends_on:
      - nginx-proxy
    volumes:
      - ./bura-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm run generate-cards && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_TG_BOT_TOKEN=${REACT_APP_TG_BOT_TOKEN}
      - REACT_APP_GAME_MIN_PLAYERS=${REACT_APP_GAME_MIN_PLAYERS}
      - REACT_APP_GAME_MAX_PLAYERS=${REACT_APP_GAME_MAX_PLAYERS}
      - REACT_APP_GAME_WIN_POINTS=${REACT_APP_GAME_WIN_POINTS}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
      - REACT_APP_ENV=${REACT_APP_ENV}
      - VIRTUAL_HOST=bura.loc
      - VIRTUAL_PORT=3000
    networks:
      - bura-network
        
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/dev/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ~/dev/certs/:/etc/nginx/certs:delegated
      - ./devops/nginx/conf.d:/etc/nginx/conf.d
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bura-network

volumes:
  db_data:
  cache:
    driver: local

networks:
  bura-network:
    driver: bridge
